FROM oven/bun:1.3.5-alpine

ENV NODE_ENV=development
ENV APP_ENV=dev

WORKDIR /app

COPY . .

# Install system dependencies
RUN apk add --no-cache poppler-utils curl

RUN bun install

WORKDIR /app

# Entrypoint script
ENTRYPOINT ["./docker-entrypoint.sh"]

# Start the application
CMD ["bun", "run", "dev"]
