FROM oven/bun:1.3.9-slim

ENV NODE_ENV=development
ENV APP_ENV=dev

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    poppler-utils \
    curl \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock ./

RUN bun install

COPY . .

# Entrypoint script
ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["bun", "run", "dev"]
